import Link from "next/link"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <h1>Sistema: Olá mundo</h1>
        <nav>
          <ul>
            <li> <Link href = "/"> Home</Link></li>
            <li> <Link href="/users"> Usuários</Link></li>
            <li> <Link href="/login"> Login</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
